=== luisfesu/SEW_XML/arbolGenealogico.dtd
<!ELEMENT familiares (familiar+)>
<!ELEMENT familiar (fecha, lugarNacimiento, coordenadas, 
    fecha?, lugarFallecimiento?, coordenadas?, retrato+ , familiar?, familiar?)>

<!ELEMENT coordenadas EMPTY>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT lugarNacimiento (#PCDATA)>
<!ELEMENT lugarFallecimiento (#PCDATA)>

<!ELEMENT retrato (#PCDATA)>


<!-- Familiar: -->
<!ATTLIST familiar nombre CDATA #REQUIRED>
<!ATTLIST familiar apellido CDATA #REQUIRED>

<!-- coordenadas: -->
<!ATTLIST coordenadas 
    nombre CDATA #REQUIRED 
    latitud CDATA #REQUIRED 
    longitud CDATA #REQUIRED 
    altitud CDATA #REQUIRED
>

<!-- Fecha: -->
<!ATTLIST fecha nombre CDATA #REQUIRED>

<!-- Retratos: -->
<!ATTLIST retrato filename CDATA #REQUIRED>

=== luisfesu/SEW_XML/arbolGenealogico.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arbolGenealogico SYSTEM "arbolGenealogico.dtd">
<familiares>
    <familiar nombre="Luis" apellido="Fernandez">

        <fecha nombre="Fecha de Nacimiento"> 03/02/2000 </fecha>
        <lugarNacimiento>"Gijon"</lugarNacimiento>
        <coordenadas nombre="Lugar de nacimiento" latitud="1" longitud="2" altitud="3" />
        <retrato filename="foto-luis.jpg">Retrato de Luis</retrato>
       
        <familiar nombre = "Jose" apellido="Fernandez">

            <fecha nombre="Fecha de Nacimiento"> 03/02/1975 </fecha>
            <lugarNacimiento>"Aviles"</lugarNacimiento>
            <coordenadas nombre="Lugar de nacimiento" latitud="3" longitud="3" altitud="4" />
            <retrato filename="foto-jose.jpg">Retrato de Jose</retrato>
            
            <familiar nombre = "Manuel" apellido="Fernandez">

                <fecha nombre="Fecha de Nacimiento"> 03/02/1930 </fecha>
                <lugarNacimiento>"Aviles"</lugarNacimiento>
                <coordenadas nombre="Lugar de nacimiento" latitud="3" longitud="3" altitud="4" />
                <!-- Fallecimiento: -->
                <fecha nombre="Fecha de Fallecimiento"> 15/12/2005 </fecha>
                <lugarFallecimiento>"Oviedo"</lugarFallecimiento>
                <coordenadas nombre="Lugar de nacimiento" latitud="6" longitud="6" altitud="1" />

                <retrato filename="foto-manuel.jpg">Retrato de Manuel</retrato>

            </familiar>

        </familiar>

        <familiar nombre = "Angeles" apellido="Suarez">

            <fecha nombre="Fecha de Nacimiento"> 03/02/1975 </fecha>
            <lugarNacimiento>"Gijon"</lugarNacimiento>
            <coordenadas nombre="Lugar de nacimiento" latitud="4" longitud="5" altitud="6" />
            <retrato filename="foto-angeles.jpg">Retrato de Angles</retrato>

        </familiar>

    </familiar>
</familiares>
